#include<stdio.h>
#include<string.h>
int main()
{
    char s[100];
    int y;
    while(scanf("%s",s)!=EOF){
        y=0;
        if(s[0]>='0'&&s[0]<='9')y=1;


        if(y==1){
            int n,i=0,j,m;
            n=0;
            for(i=0;s[i];i++)n=n*10+(s[i]-'0');
    m=n;
    i=0;
    for(j=0;j<n/1000;j++){
            s[i]='M';
            i++;
    }
    n=n%1000;
    if((n+100)/1000==1){
        s[i]='C';
        i++;
        s[i]='M';
        i++;
        n=n-900;
    }
    for(j=0;j<n/500;j++){
        s[i]='D';
        i++;
    }
    n=n%500;
    if((n+100)/500==1){
        s[i]='C';
        i++;
        s[i]='D';
        i++;
        n=n-400;
    }
    for(j=0;j<n/100;j++){
        s[i]='C';
        i++;
    }
    n=n%100;
    if((n+10)/100==1){
        s[i]='X';
        i++;
        s[i]='C';
        i++;
        n=n-90;
    }
    for(j=0;j<n/50;j++){
        s[i]='L';
        i++;
    }
    n=n%50;
    if((n+10)/50==1){
        s[i]='X';
        i++;
        s[i]='L';
        i++;
        n=n-40;
    }
    for(j=0;j<n/10;j++){
        s[i]='X';
        i++;
    }
    n=n%10;
    if((n+1)/10==1){
        s[i]='I';
        i++;
        s[i]='X';
        i++;
        n=n-9;
    }
    for(j=0;j<n/5;j++){
        s[i]='V';
        i++;
    }
    n=n%5;
    if((n+1)/5==1){
        s[i]='I';
        i++;
        s[i]='V';
        i++;
        n=n-4;
    }
    for(j=0;j<n;j++){
        s[i]='I';
        i++;
    }
    s[i]='\0';
    printf("%s\n",s);
        }
        else{
            int i,n=0,j;
    for(i=0;s[i]!='\0';i++){
        if(s[i]=='M'){
                n=n+1000;
        }
        else if(s[i]=='C'&&s[i+1]=='M'){
            n=n+900;
            i++;
        }
        if(s[i]=='D'){
                n=n+500;
        }
        else if(s[i]=='C'&&s[i+1]=='D'){
            n=n+400;
            i++;
        }
        if(s[i]=='C'){n=n+100;
        }
        else if(s[i]=='X'&&s[i+1]=='C'){
            n=n+90;
            i++;
        }
        if(s[i]=='L'){n=n+50;
        }
        else if(s[i]=='X'&&s[i+1]=='L'){
            n=n+40;
            i++;
        }
        if(s[i]=='X'){n=n+10;
        }
        else if(s[i]=='I'&&s[i+1]=='X'){
            n=n+9;
            i++;
        }
        if(s[i]=='V'){n=n+5;
        }
        else if(s[i]=='I'&&s[i+1]=='V'){
            n=n+4;
            i++;
        }
        if(s[i]=='I'){n=n+1;
        }
    }
    printf("%d\n",n);
        }
    }
}
